server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: clinic-service
          uri: lb://clinic-service
          predicates:
            - Path=/api/clinics/**
        - id: package-service
          uri: lb://package-service
          predicates:
            - Path=/api/packages/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/api/schedules/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: promo-service
          uri: lb://promo-service
          predicates:
            - Path=/api/promos/**
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/api/staff/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: medicalhistory-service
          uri: lb://medicalhistory-service
          predicates:
            - Path=/api/medical-history/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedback/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**
        - id: referral-service
          uri: lb://referral-service
          predicates:
            - Path=/api/referrals/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/audit/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 