server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        # Example route
        - id: example-service
          uri: http://localhost:8081
          predicates:
            - Path=/example/**

# Eureka client config
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true 