server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT Configuration (should match auth-service)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000  # 1 hour in milliseconds
  refresh-expiration: 86400000  # 24 hours in milliseconds

# Logging
logging:
  level:
    com.clinicsys.user: DEBUG
    org.springframework.security: DEBUG
    com.clinicsys.user.config.JwtAuthenticationFilter: DEBUG
    org.springframework.web.filter.OncePerRequestFilter: DEBUG 